version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errname
    - errorlint
    - gocritic

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cloudygreybeard/longsocks
